# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PrIxc0lc7UifaBVW4mCciki5BxCS75xk
"""

# !pip install neo4j langchain langchain_openai -q

from langchain.chains import GraphCypherQAChain
from langchain_community.graphs import Neo4jGraph
from langchain.chat_models import ChatOpenAI

graph = Neo4jGraph(
    url="neo4j+s://3262e8ec.databases.neo4j.io", username="neo4j", password="EczMYMfSJiSm7bmEqWQHCnfdewEgWQtG9gr41FXHYF0"
)

graph.refresh_schema()
print(graph.schema)

import os

os.environ["OPENAI_API_KEY"] = "sk-xx"

chain = GraphCypherQAChain.from_llm(
    ChatOpenAI(temperature=0, model= "gpt-4-1106-preview"),
    graph=graph,
    verbose=True,
    top_k=1000
)

results = chain.run("""
I want to learn about "part of speech tagging", what concepts should I learn first?
Return all prerequisites, including direct or indirect.
Return in json format.

 Example:
 A->B->C
 If i want to learn C, I need to learn B, and B needs A.
 So I need learn A and B.
 """)

print(results)

